export interface TransactionDetailsDTO {
  id: string;
  type: string;
  tipo: string;
  tipoTransacao: string;
  status: string;
  description: string | null;
  descricao: string | null;
  observations?: string | null;
  observacao?: string | null;
  observacoes?: string | null;
  amount: number;
  valor: number;
  grossAmount?: number | null;
  netAmount?: number | null;
  fees?: number | null;
  discount?: number | null;
  taxes?: number | null;
  interest?: number | null;
  fine?: number | null;
  currency?: string | null;
  transactionDate?: string | null;
  dataTransacao?: string | null;
  data_transacao?: string | null;
  data?: string | null;
  competence?: string | null;
  dueDate?: string | null;
  paidAt?: string | null;
  recurrence?: string | null;
  paymentMethod?: string | null;
  formaPagamento?: string | null;
  paymentType?: string | null;
  tipoPagamento?: string | null;
  installments?: number | null;
  quantidadeParcelas?: number | string | null;
  installmentCurrent?: number | null;
  bankAccount?: Record<string, unknown> | string | null;
  category?: Record<string, unknown> | string | null;
  categoria?: string | null;
  subcategory?: Record<string, unknown> | string | null;
  subcategoria?: string | null;
  costCenter?: Record<string, unknown> | string | null;
  tags?: string[];
  labels?: string[];
  attachments?: Array<Record<string, unknown>>;
  artist?: Record<string, unknown> | null;
  artist_id?: string | null;
  artistaVinculado?: string | null;
  project?: Record<string, unknown> | null;
  projeto_id?: string | null;
  projetoVinculado?: string | null;
  campaign?: Record<string, unknown> | null;
  contract?: Record<string, unknown> | null;
  contrato_id?: string | null;
  contratoVinculado?: string | null;
  release?: Record<string, unknown> | null;
  event?: Record<string, unknown> | null;
  evento_id?: string | null;
  eventoVinculado?: string | null;
  client?: Record<string, unknown> | string | null;
  fornecedorCliente?: string | null;
  supplier?: Record<string, unknown> | string | null;
  metadata: Record<string, unknown>;
  createdBy?: Record<string, unknown> | string | null;
  updatedBy?: Record<string, unknown> | string | null;
  createdAt: string;
  created_at: string;
  updatedAt: string;
  updated_at: string;
}
